### ISSUE TITLE
Cant find anything?

### ISSUE THREAD

**Issue by stormplayer** [coderCleric/Mindscapes#1]
It is probably my fault but I cannot find any  content in this mod. 

In the ship log it says there is something new in the observatory but there is nothing there.
I tried a bunch of things i got no clue what im doing

**Comment by coderCleric** [comment]
Are there any errors in the console? Also, did you check to the left of the wall with the Nomai writing?

**Comment by stormplayer** [comment]
You know that's my bad, I looked directly at that and thought it had always been there. Thank you I'm looking forward to playing it
